### ISSUE TITLE
'Client' object has no attribute 'start_workers'

### ISSUE THREAD

**Issue by basnijholt** [dask/dask-drmaa#12]
In the `README` the following is written
```
from dask_drmaa import DRMAACluster
cluster = DRMAACluster()

from dask.distributed import Client
client = Client(cluster)
client.start_workers(2)
```

However, this leads to: `AttributeError: 'Client' object has no attribute 'start_workers'`

What does work is:
```
from dask_drmaa import DRMAACluster
cluster = DRMAACluster()
cluster.start_workers(10) 
```

Don't know if this is incorrect in the `README` or a bug. I use PBS.

**Comment by mrocklin** [comment]
Correct, should be cluster.start_workers
