### ISSUE TITLE
Releasing?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-drmaa#39]
Any thoughts on getting this tagged, on to PyPI, and on to conda-forge? Is this stable enough at this point to do those things or are there other things needed to be done first?

**Comment by mrocklin** [comment]
It's probably stable enough for a release.

**Comment by jakirkham** [comment]
Cool. Was going to try and get a `MANIFEST.in` added to package the README and LICENSE. ( https://github.com/dask/dask-drmaa/pull/40 ) Not sure if there are other things we should make sure land in the sdist. Could you please take a look and let me know?

In the process of making that PR. Saw this test failure ( https://github.com/dask/dask-drmaa/issues/41 ). As I doubt adding the `MANIFEST.in` would have caused this, would assume this is a failure that `master` would also be affected by. Having only started playing with `dask-drmaa`, I don't really know much about that test or the failure it is experiencing. Would really appreciate any thoughts/advice on it (if you have any).

**Comment by jakirkham** [comment]
Would also add there is another test failure ( https://github.com/dask/dask-drmaa/issues/42 ). Both of these appear to be somewhat sporadic, but do reoccur. Not sure if there is some timing issue or what.

**Comment by jakirkham** [comment]
So I don't think the test failures should be blocking for the release, but would like to revisit them down the road. If you agree, I think roughly these are our next steps.

1. Add the git tag and publish on GitHub. (any preferences for how we do this?)
2. Publish to PyPI. (can share permissions with others if there is interest)
3. Publish to conda-forge.

Any thoughts on these steps? Additions/Modifications?

**Comment by jakirkham** [comment]
Also you have been pretty busy here lately @TomAugspurger. Do you have any thoughts on this?

**Comment by jakirkham** [comment]
So I think this should be basically ready to release. Would like PR ( https://github.com/dask/dask-drmaa/pull/45 ) to land as well to make the release process less cumbersome. Other than that am planning on tagging `0.1.0` tomorrow. Will then deploy it to PyPI and conda-forge. If there are any concerns, please don't hesitate to let me know. If I don't hear anything, will assume that we are all on board with this plan.

**Comment by mrocklin** [comment]
No concerns from me.  Thank you for pushing ahead with this.

**Comment by jcftang** [comment]
For me it would be nice if https://github.com/dask/dask-drmaa/pull/33 or https://github.com/dask/dask-drmaa/pull/46 gets merged before things are tagged, I use slurm at our site and it would be nice if it worked out of the box.

**Comment by jakirkham** [comment]
It looks like with the first one there are some unaddressed review comments and it appears to be dormant. Maybe it is worth taking that one over if it is interesting to you?

The other one was just put up an hour ago. Would like us to avoid a mad dash with changes that will affect the codebase at any deeper level than say packaging fixes at this stage. The rationale being that we seem to be pretty comfortable with releasing it in its current state. Also there is still a bit of work to get that done as there has not been a release yet. Since it seems like we are shy reviewers that would be able to look at those sorts of changes, it seems better to get the release out as is an then revisit.

That said, would be happy to see this released as often as needed. Should be a lot easier after the first release goes out. So I think it is pretty reasonable to look at SLURM support or any other interesting things say for the next release. Does that seem reasonable?

**Comment by jcftang** [comment]
@jakirkham that sounds reasonable for me, #46 is just a rehash of #33 they do the same thing.

**Comment by jakirkham** [comment]
Thanks @jcftang. Will follow-up on those once this is complete.

**Comment by jakirkham** [comment]
Have submitted a PyPI package just now. The conda-forge recipe is submitted in PR ( https://github.com/conda-forge/staged-recipes/pull/4381 ). Would be good if a few people looked it over to make sure I have not missed anything.

**Comment by jakirkham** [comment]
Package is now available on conda-forge. Closing as resolved.
