### ISSUE TITLE
Where to find dask-worker

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-drmaa#5]
Currently we assume that the `dask-worker` executable is in the same absolute location on all slaves as it is on the client machine.  I'm not sure what the standard assumption is.  It seems that there are a few options:

1.  Use absolute location of client process
2.  Use `dask-worker` and trust PATH on the slaves to find the right location
3.  Use `dask-worker` and convey the local user environment to jobs
4.  ?

**Comment by davidr** [comment]
In most cases I know of, the absolute location is consistent across an entire cluster. Most MPI implementations for instance require mpiexec/mpirun to be in the same path on all machines. I think (1) is acceptable.

**Comment by mrocklin** [comment]
Grand.  That's what we do now.  Closing.
