### ISSUE TITLE
Work stealing is not happening

### ISSUE THREAD

**Issue by daniel-sch** [dask/dask-drmaa#51]
When the load on all workers is not evenly distributed, no work stealing is performed.

One way to provoke this, is to submit the jobs first and start the workers afterwards. Then the worker that starts first will get all jobs assigned and all other workers will be idle. However, this is also happening if the workers get started first and the execution time of the jobs differs very much.

In the web interface under `/stealing`, the idle and saturated workers are correctly displayed.

I wrote a little MWE:
```
import time
import dask.multiprocessing
from dask.distributed import Client
from dask_drmaa import SGECluster

def execute(sleep_time):
    import time
    
    time.sleep(sleep_time)
    return sleep_time

if __name__ == "__main__":
    times = [60, 60, 60, 60, 1, 1, 1, 1]
    lazy_results = [dask.delayed(execute)(sleep_time) for sleep_time in times]
    
    cluster = SGECluster()
    client = Client(cluster)
    cluster.start_workers(2)
    
    results = dask.compute(*lazy_results, get=client.get)
    print(results)
    
    cluster.close()
```

I don't know if this is really a bug in dask-drmaa or if it is in dask.distributed, but I submitted it here because I can't really reproduce this with `LocalCluster`.

I use a fully updated version of Anaconda with Python 3.6 on Linux. The packages are installed in the following versions:

```
dask                      0.16.0           py36h73d177f_0
dask-core                 0.16.0           py36ha827fd6_0
dask-drmaa                0.1.0                     <pip>
distributed               1.20.2                   py36_0
```

Happy holidays and thanks for your help. Please let me know if you need any further information.

**Comment by mrocklin** [comment]
Thank you for the clean bug report and minimal example.

If what you are saying is correct, that work stealing is not working, then
I recommend trying to make an example using only LocalCluster, perhaps by
adding workers part way in, and then submitting an issue to
github.com/dask/distributed .  I do not currently see any reason why doing
this on DRMAA would be any different.  (although apparently you've tried
this and haven't found much).  The odds of getting someone to spin up a
DRMAA cluster to check your example are lower than getting someone to run
something locally.

**Comment by daniel-sch** [comment]
Thank you for your help. I managed to reproduce this with `LocalCluster` and submitted a new issue [here](https://github.com/dask/distributed/issues/1654).
