### ISSUE TITLE
Munge authentication failure on SGE

### ISSUE THREAD

**Issue by ptooley** [dask/dask-drmaa#53]
I am having an issue with submitting tasks on SGE where is appears that cleanup_closed_workers callback is failing to execute correctly due to an authentication issue.

Job submission appears to work, as does job deletion at exit, just the polling from the callback fails.

```
In [1]: from dask_drmaa import DRMAACluster, Adaptive

In [2]: cluster = DRMAACluster()

In [3]: cluster.start_workers(1)

In [4]: tornado.application - ERROR - Exception in callback <bound method DRMAACluster.cleanup_closed_workers of <DRMAACluster: 1 workers>>
Traceback (most recent call last):
  File "/home/ac1mpt/.conda/envs/condagpu/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/home/ac1mpt/repos/dask-drmaa/dask_drmaa/core.py", line 251, in cleanup_closed_workers
    if get_session().jobStatus(jid) in ('closed', 'done'):
  File "/home/ac1mpt/.conda/envs/condagpu/lib/python3.6/site-packages/drmaa/session.py", line 520, in jobStatus
    c(drmaa_job_ps, jobId, byref(status))
  File "/home/ac1mpt/.conda/envs/condagpu/lib/python3.6/site-packages/drmaa/helpers.py", line 303, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/home/ac1mpt/.conda/envs/condagpu/lib/python3.6/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
drmaa.errors.DrmCommunicationException: code 2: MUNGE authentication failed: Invalid credential format
```

**Comment by ptooley** [comment]
To clarify I am trying to run on a Son of Grid Engine cluster.

**Comment by mrocklin** [comment]
it looks like, for some reason, calling jobStatus failed inside DRMAA.
Unfortunately I'm not personally familiar enough with DRMAA to diagnose
this.  You might want to ask upstream at
https://github.com/pygridtools/drmaa-python ?

**Comment by ptooley** [comment]
Thanks for getting back to me, it looks like under some circumstances python-drmaa fails in a multithreaded/multiprocess environment.  (See https://github.com/pygridtools/drmaa-python/issues/44 which it turns out was reported by someone else using the same cluster I am.)

I think my options are to either figure out how python-drmaa is failing or write my own cluster manager implementation that uses IPC instead of coroutines to ensure all drmaa interaction is done within a single thread (ugh.)

**Comment by jakirkham** [comment]
In that case, is it alright if we close this issue out given that this is an upstream issue?

**Comment by ptooley** [comment]
Sure. I'll let you know if I turn up anything that could be fixed in dask-drmaa

**Comment by jakirkham** [comment]
Sounds good. Thanks @ptooley.
