### ISSUE TITLE
How to limit number of threads for a DRMAACluster worker?

### ISSUE THREAD

**Issue by edurand** [dask/dask-drmaa#72]
Hello,

When starting workers on a DRMAACluster, they always use many threads
```
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          28
distributed.worker - INFO -                Memory:                    280GB
```

The actual number of threads differs from one worker to the next. 
Is there a way to limit workers to one thread? Using so many threads causes my jobs to exceed memory limits and die.

Thanks!

**Comment by lesteve** [comment]
I have not used it, but looking at the source code, I believe you can use the `args` argument in `DRMAACluster` to pass additional arguments to dask-workers:
https://github.com/dask/dask-drmaa/blob/5c235a4db27d3bbaaa171e2f35ac3cb4d88ffbd6/dask_drmaa/core.py#L104-L105

**Comment by edurand** [comment]
Thanks! I was able to figure it out by digging through the code, but the docstring for DRMAACluster really is misleading. In the end, here is what worked for me:
```
cluster = DRMAACluster(template={'nativeSpecification': {...}, 'args': ['--nthreads', '1', '--nprocs', '1']})
```
Note that putting the arg name and value in the same string does not work (e.g. `--nthreads 1` will raise an error `Error: no such option: --nthreads 1`)

**Comment by jakirkham** [comment]
Indeed. This is what we have used.

```python
dask_drmaa.DRMAACluster(template={"args": ["--nthreads", "1"]})
```

[`--nprocs` defaults to `1`]( https://github.com/dask/distributed/blob/1.21.5/distributed/cli/dask_worker.py#L64-L65 ), but can't hurt to have it explicitly.

**Comment by jakirkham** [comment]
Should add this raises the question of whether we should just default to `1` thread and allow the user to override this as needed. Thoughts?

**Comment by edurand** [comment]
@lesteve, thanks again for your help. I'll try making a PR asap.

@jakirham, I'm actually unsure if one thread is the intended behavior, or if users are maybe not supposed to call DRMAACluster directly, instead using SGECluster? SGECluster defaults to using one thread per worker.

**Comment by edurand** [comment]
Created [pull request](https://github.com/dask/dask-drmaa/pull/74) with fleshed out docstring
