### ISSUE TITLE
outputPath and errorPath are ignored

### ISSUE THREAD

**Issue by MaxNoe** [dask/dask-drmaa#79]
Related to #76

**Comment by jakirkham** [comment]
So is it that they are ignored or is it that they need to be specified via `template`?

**Comment by MaxNoe** [comment]
Yes, this was basically lying documentation. The docstring mentioned the parameters as `**kwargs` not as possible keys for `template`. Got fixed by merging #74

**Comment by jakirkham** [comment]
Thanks @MaxNoe :)
