### ISSUE TITLE
Amazon ECS?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-drmaa#8]
How would one go about using this with say Amazon ECS?

**Comment by mrocklin** [comment]
I wouldn't.  Instead I would build another similar system that launched and destroyed containers using the Amazon ECS API.   There are/will be many of these small projects.  The easiest / most similar to ECS is possibly dask-marathon: https://github.com/mrocklin/dask-marathon

I would love to see people build these out.  I'm happy to help.  See http://matthewrocklin.com/blog/work/2016/09/22/cluster-deployments

**Comment by mrocklin** [comment]
Closing as out of scope.
