### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MaxNoe** [dask/dask-drmaa#82]
I think with the fixes in #74 , #78 and #75 a version 2.1 could be released, what do yo think?

**Comment by jakirkham** [comment]
Releasing is a good idea.

Was eyeing PR ( https://github.com/dask/dask-drmaa/pull/81 ) as one last patch before tagging. Help testing it would be welcome. That said, it doesn't strictly need to be in the release.

**Comment by mrocklin** [comment]
Releasing seems good to me, although I must admit that I probably know less about the current status here than @jakirkham

**Comment by jakirkham** [comment]
Available as 0.2.1 on PyPI and conda-forge. Thanks everyone for contributing. Enjoy! :)

**Comment by mrocklin** [comment]
Thanks for doing the release @jakirkham !
