### ISSUE TITLE
Give absolute path to worker script

### ISSUE THREAD

**Issue by MaxNoe** [dask/dask-drmaa#87]
Starting workers fails (at least on slurm) if the `template['workingDirectory']` is not the current working directory because:

```
/var/spool/slurm/d/job1177731/slurm_script: line 2: ./dask-worker-scriptz8gmf_cpsh: No such file or directory
```

**Comment by jakirkham** [comment]
SGTM. Care to try a PR?

**Comment by MaxNoe** [comment]
Working on it ;)

**Comment by MaxNoe** [comment]
See #90

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/dask/dask-drmaa/pull/90 ).
