### ISSUE TITLE
Does not work with user install of dask

### ISSUE THREAD

**Issue by MaxNoe** [dask/dask-drmaa#88]
This fails with a `pip install --user` installation, because then dask worker does not reside in 

```
worker_bin_path = os.path.join(sys.exec_prefix, 'bin', 'dask-worker')
```

But in `.local/bin`

**Comment by jakirkham** [comment]
Maybe a `python -m` approach could be used here?

**Comment by MaxNoe** [comment]
> Maybe a python -m approach could be used here?

Might also be possible. Do you think that would be preferable to `find_executable`?

**Comment by jakirkham** [comment]
Personally think this would be more robust as one can ensure the same interpreter is used (i.e `sys.executable`). So it would be something like...

```
python -m distributed.cli.dask_worker
```

FWIW tested it with `pip install --user distributed` .

ref: https://github.com/dask/distributed/blob/1.21.8/distributed/cli/dask_worker.py#L255-L256

**Comment by jakirkham** [comment]
To illustrate what this would look like, have put together PR ( https://github.com/dask/dask-drmaa/pull/91 ).
