### ISSUE TITLE
distributed.utils.ignoring no longer exists - should be replaced with contextlib.suppress

### ISSUE THREAD

**Issue by lebedov** [dask/dask-drmaa#97]
**What happened**:

Using dask-drmaa with recent versions of dask.distributed fails with the following exception:

```
~/miniconda3/lib/python3.6/site-packages/dask_drmaa/__init__.py in <module>
----> 1 from .core import DRMAACluster, get_session
      2 from .sge import SGECluster
      3 from .adaptive import Adaptive
      4
      5 from ._version import get_versions

~/miniconda3/lib/python3.6/site-packages/dask_drmaa/core.py in <module>
     14 from distributed import LocalCluster
     15 from distributed.deploy import Cluster
---> 16 from distributed.utils import log_errors, ignoring
     17 from distributed.utils import PeriodicCallback
     18

ImportError: cannot import name 'ignoring'
```

**What you expected to happen**:

No exception.

**Minimal Complete Verifiable Example**:

Install dask.distributed 2.19.0 and dask-drmaa; then run the following code:
```python
import dask_drmaa
```

**Anything else we need to know?**:

`distributed.utils.ignoring` [has been removed](https://github.com/dask/distributed/pull/3819) from dask.distributed as of 5/20/2020; dask-drmaa should be updated to use `contextlib.suppress` instead.

**Environment**:

- Dask version: 2.19.0
- Python version: 3.6.10
- Operating System: CentOS 6.10
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment]
This sounds good to me.  Are you interested in submitting a change with
this PR?

Alternatively, many dask-drmaa users have moved over to dask-jobqueue,
which is more actively maintained and generally more featureful

**Comment by lebedov** [comment]
I can submit a PR, but on further inspection it seems that there are other changes that are needed beyond the one I mentioned that would need to be made to get dask-drmaa to work with the latest version of distributed; for instance, the latter expects the use of a communicator object, while it doesn't seem that dask-drmaa currently uses one.

I actually was trying to use dask-jobqueue to run some embarrassingly parallel code on an LSF cluster, but revisited dask-drmaa because I was experiencing issues involving killed workers while scaling up my application. Given that it seems that no further development is being done on dask-drmaa and I unfortunately don't have sufficient time at the present to devote to figuring out the other fixes it needs, I'll hold off on submitting a PR unless you think that an incomplete fix is worth incorporating into the codebase.

**Comment by mrocklin** [comment]
Na, I'm personally in favor of retiring this codebase.

If you're having Issues with dask-jobqueue I do encourage you to speak up
on that issue tracker.  It has a relatively vibrant community of HPC users
around it.

**Comment by lebedov** [comment]
OK - closing. Thanks.
